<?xml version="1.0"?>
<package format="3">
  <name>tof_viz_node</name>
  <version>0.1.0</version>
  <description>ToF sensor MarkerArray visualizer for Foxglove</description>
  <maintainer email="omni@local">pi</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
